//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuiBao_v1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    [Serializable]
    public partial class wolf_testEntities : DbContext
    {
        public wolf_testEntities()
            : base("name=wolf_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<School> School { get; set; }
    }
}
