//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuiBao_v1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public decimal Num { get; set; }
        public Nullable<decimal> SchoolNum { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
