

//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SuiBao_v1.IRepository
{
    using System;
    using System.Threading.Tasks;
    
    
        public partial interface IRepositoryFactory
        {
    
    	IPeople People{get;}
    	ISchool School{get;}
        Task<int> SaveChangesAsync();
    
    	int SaveChanges();
    
    	ISqlRepository Sql { get; }
    }
    
    public partial interface IPeople:IBaseRepository<SuiBao_v1.Model.People>
    {
    }
    
    public partial interface ISchool:IBaseRepository<SuiBao_v1.Model.School>
    {
    }
    
    
}
