


//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------



namespace SuiBao_v1.Repository
{
    using System.Data.Entity;
    using System.Threading.Tasks;
    
    
        public partial class RepositoryFactory:SuiBao_v1.IRepository.IRepositoryFactory
        {
    
        public SuiBao_v1.IRepository.IPeople People
        {
           get
           {
               return new SuiBao_v1.Repository.People(SuiBao_v1.Model.OperationContext.Current);
           }
        }
        public SuiBao_v1.IRepository.ISchool School
        {
           get
           {
               return new SuiBao_v1.Repository.School(SuiBao_v1.Model.OperationContext.Current);
           }
        }
         public async Task<int> SaveChangesAsync()
         {
             return await SuiBao_v1.Model.OperationContext.SaveChangesAsync();
         }
    
    	 public int SaveChanges()
         {
             return SuiBao_v1.Model.OperationContext.SaveChanges();
         }
    
    	    public IRepository.ISqlRepository Sql
            {
                get
                {
                    return new SqlRepository();
                }
            }
        }
    
         public partial class People:BaseRepository<SuiBao_v1.Model.People>,SuiBao_v1.IRepository.IPeople
         {
    		public People(DbContext context) : base(context)
            {
            }
         }
    
         public partial class School:BaseRepository<SuiBao_v1.Model.School>,SuiBao_v1.IRepository.ISchool
         {
    		public School(DbContext context) : base(context)
            {
            }
         }
    
    
}
